



user_data = [

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili1@gmail.com",
    "number": "555706163" ,
    "personal_id": "01010101129" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},


{
    "name": "giorgi" ,
    "lastname": "komasuridze" ,
    "email": "giorgi.komasuridze@gmail.com",
    "number": "555706168" ,
    "personal_id": "01010101153" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "komasuridze" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 1, 
},

{
    "name": "sergo" ,
    "lastname": "sergishvili" ,
    "email": "sergo.sergo@gmail.com",
    "number": "555706167" ,
    "personal_id": "01010401123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "sergishvili" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა", 
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "მათემატიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 3, 
},

{
    "name": "ruso" ,
    "lastname": "kevlishvili" ,
    "email": "ruso.kevlishvili@gmail.com",
    "number": "555706166" ,
    "personal_id": "01010171123" ,
    "date": "2013-02-02T24",
    "gender": "female",
    "password": "kevlishvili" ,
    "country_id": 1,
    "region_id": 2,
    "city_id": 3,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ქიმია",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 4, 
},

{
    "name": "badri" ,
    "lastname": "esebua" ,
    "email": "badri.esebua@gmail.com",
    "number": "555706163" ,
    "personal_id": "01010401125" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "esebua" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "საერთაშორისო ურთიერთობები",
    "semester": 6 ,
    "degree_level": "დოქტორანტი",
    "role": 5, 
},

{
    "name": "albert" ,
    "lastname": "ainshtaini" ,
    "email": "albert.ainshtaini@gmail.com",
    "number": "555706163" ,
    "personal_id": "01510101124" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "ainshtaini" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "დოქტორი",
    "role": 2, 
},

{
    "name": "besik" ,
    "lastname": "araxamia" ,
    "email": "besik.araxamia@gmail.com",
    "number": "555706163" ,
    "personal_id": "01017101123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "araxamia" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ბიოლოგია",
    "semester": 6 ,
    "degree_level": "მაგისტრატურა",
    "role": 1, 
},

{
    "name": "nino" ,
    "lastname": "medvedevi" ,
    "email": "nino.medvedevi@gmail.com",
    "number": "55570616" ,
    "personal_id": "01010144122" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "medvedevi" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 3, 
},

{
    "name": "soso" ,
    "lastname": "gawerava" ,
    "email": "soso.gawerava@gmail.com",
    "number": "555706161" ,
    "personal_id": "44010101123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "gawerava" ,
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": "null" ,
    "grade": "null" ,
    "parent_name": "null",
    "parent_lastname": "null",
    "parent_number": "null" ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 4, 
},






]