



user_data = [

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706163" ,
    "personal_id": "01010101129" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},


{
    "name": "giorgi" ,
    "lastname": "tvalabeishvili" ,
    "email": "giorgi.tvalabeishvili@gmail.com",
    "number": "555706168" ,
    "personal_id": "01010101153" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "giorgi" ,
    "conf_password": "giorgi" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "sergo" ,
    "lastname": "sergishvili" ,
    "email": "sergo.sergo@gmail.com",
    "number": "555706167" ,
    "personal_id": "01010401123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "sergo" ,
    "conf_password": "sergo" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა", 
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 1, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706166" ,
    "personal_id": "01010171123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706163" ,
    "personal_id": "01010401125" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706163" ,
    "personal_id": "01510101124" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706163" ,
    "personal_id": "01017101123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706163" ,
    "personal_id": "01010144122" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},

{
    "name": "Anri" ,
    "lastname": "tvalabeishvili" ,
    "email": "anri.tvalabeishvili@gmail.com",
    "number": "555706161" ,
    "personal_id": "44010101123" ,
    "date": "2013-02-02T24",
    "gender": "Male",
    "password": "tvalabeishvili" ,
    "conf_password": "tvalabeishvili" , 
    "country_id": 1,
    "region_id": 1,
    "city_id": 2,
    "address": "დიდი დიღომი პეტრიწის 16ა",
    "school": None ,
    "grade": None ,
    "parent_name": None,
    "parent_lastname": None,
    "parent_number": None ,
    "university_id": 1,
    "faculty": "ზუსტ და საბუნებისმეტყველო მეცნიერებათა ფაკულტეტი",
    "program": "ფიზიკა",
    "semester": 6 ,
    "degree_level": "ბაკალავრი",
    "role": 2, 
},









]